"""
Markdown output formatter for SignalPulse-CLI.

Generates Markdown reports from signal data suitable for
saving to files or displaying in markdown viewers.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from ..config import Config
from ..sources.base import SignalItem
from ..utils import format_relative_time, format_number, extract_domain, utc_now


class MarkdownFormatter:
    """Markdown report formatter.

    Generates clean, well-structured Markdown documents from
    signal data and AI briefings.

    Attributes:
        config: Application configuration.
    """

    def __init__(self, config: Config) -> None:
        """Initialize the Markdown formatter.

        Args:
            config: Application configuration.
        """
        self.config = config

    def render_items(
        self, items: List[SignalItem], title: str = "Signal Pulse Report"
    ) -> str:
        """Render signal items as a Markdown document.

        Generates a complete Markdown report with a header, source
        summary table, and individual item listings.

        Args:
            items: List of scored SignalItem objects.
            title: Report title.

        Returns:
            Complete Markdown document as a string.
        """
        lines: List[str] = []

        # Header
        lines.append(f"# {title}\n")
        lines.append(
            f"> Generated by **SignalPulse-CLI** on "
            f"{utc_now().strftime('%Y-%m-%d %H:%M UTC')} | "
            f"{len(items)} signals aggregated\n"
        )
        lines.append("")

        # Source summary
        source_counts: Dict[str, int] = {}
        for item in items:
            source_counts[item.source] = source_counts.get(item.source, 0) + 1

        if source_counts:
            lines.append("## Sources\n")
            lines.append("| Source | Items |")
            lines.append("|--------|-------|")
            for source, count in sorted(
                source_counts.items(), key=lambda x: -x[1]
            ):
                label = source.capitalize()
                lines.append(f"| {label} | {count} |")
            lines.append("")

        # Top items table
        lines.append("## Top Signals\n")
        lines.append("| # | Source | Score | Title | Domain | Age | Comments |")
        lines.append("|---|--------|-------|-------|--------|-----|----------|")

        for i, item in enumerate(items, 1):
            source = item.source.capitalize()
            score = f"{item.normalized_score:.0%}"
            title = self._escape_markdown(item.title[:100])
            domain = extract_domain(item.url) if item.url else "-"
            age = format_relative_time(item.created_at)
            comments = format_number(item.comments)

            lines.append(
                f"| {i} | {source} | {score} | {title} | {domain} | "
                f"{age} | {comments} |"
            )

        lines.append("")

        # Detailed item listings
        lines.append("## Detailed Listings\n")
        for i, item in enumerate(items, 1):
            lines.append(f"### {i}. {self._escape_markdown(item.title)}\n")
            lines.append(f"- **Source**: {item.source.capitalize()}")
            lines.append(f"- **Score**: {item.normalized_score:.1%}")
            lines.append(f"- **Comments**: {item.comments}")
            if item.url:
                lines.append(f"- **URL**: [{extract_domain(item.url)}]({item.url})")
            if item.author:
                lines.append(f"- **Author**: {item.author}")
            lines.append(f"- **Age**: {format_relative_time(item.created_at)}")

            # Source-specific details
            if item.source == "github":
                lang = item.metadata.get("language", "Unknown")
                stars = item.metadata.get("stars", 0)
                forks = item.metadata.get("forks", 0)
                lines.append(f"- **Language**: {lang}")
                lines.append(f"- **Stars**: {format_number(stars)}")
                lines.append(f"- **Forks**: {format_number(forks)}")
            elif item.source == "reddit":
                subreddit = item.metadata.get("subreddit", "")
                if subreddit:
                    lines.append(f"- **Subreddit**: r/{subreddit}")
            elif item.source == "producthunt":
                topics = item.metadata.get("topics", [])
                if topics:
                    lines.append(f"- **Topics**: {', '.join(topics[:5])}")

            lines.append("")

        return "\n".join(lines)

    def render_briefing(self, briefing: str) -> str:
        """Render an AI briefing as Markdown.

        Wraps the briefing in a header section.

        Args:
            briefing: Markdown-formatted briefing text.

        Returns:
            Complete Markdown document with the briefing.
        """
        lines: List[str] = []
        lines.append("# AI Intelligence Briefing\n")
        lines.append(
            f"> Generated by **SignalPulse-CLI** on "
            f"{utc_now().strftime('%Y-%m-%d %H:%M UTC')}\n"
        )
        lines.append("---\n")
        lines.append(briefing)
        lines.append("")
        return "\n".join(lines)

    def render_full_report(
        self, items: List[SignalItem], briefing: Optional[str] = None
    ) -> str:
        """Render a complete report with items and optional AI briefing.

        Args:
            items: List of scored SignalItem objects.
            briefing: Optional AI briefing text.

        Returns:
            Complete Markdown report document.
        """
        report = self.render_items(items, title="SignalPulse Intelligence Report")

        if briefing:
            report += "\n---\n\n"
            report += self.render_briefing(briefing)

        return report

    @staticmethod
    def _escape_markdown(text: str) -> str:
        """Escape special Markdown characters in text.

        Handles pipe, asterisk, underscore, and hash characters
        that could break Markdown table formatting.

        Args:
            text: Raw text to escape.

        Returns:
            Escaped text safe for Markdown rendering.
        """
        # Only escape characters that would break table formatting
        replacements = [
            ("|", "\\|"),
        ]
        for old, new in replacements:
            text = text.replace(old, new)
        return text
